import type { Env } from "../config/env";
import type { MembershipTier, Offer } from "./types";

const enterpriseApplication = "/contact#apply-enterprise";
const creatorApplication = "/contact#apply-creator";
const musicApplication = "/contact#apply-music";
const travelApplication = "/contact#apply-travel";

export function getEnterpriseOffers(env: Env): Offer[] {
  return [
    {
      brand: "jaypventuresllc",
      lane: "enterprise_services",
      publicSlug: "fit-call-15",
      title: "JayPVentures LLC Fit Call · 15 Minutes",
      summary: "Fast alignment call for founders and operators who need the right lane before committing to deeper work.",
      displayedPrice: "Free",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Best for qualified founders, operators, and teams assessing fit.",
      ctaLabel: "Book Fit Call",
      badges: ["Fast Qualifier", "Enterprise First"],
    },
    {
      brand: "jaypventuresllc",
      lane: "enterprise_services",
      publicSlug: "consultation-30",
      title: "Consultation · 30 Minutes",
      summary: "Direct advisory on infrastructure, monetization, governance, and execution bottlenecks.",
      displayedPrice: "$175",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use when there is already a live system, offer, or decision in motion.",
      ctaLabel: "Book Consultation",
      badges: ["Paid Advisory"],
    },
    {
      brand: "jaypventuresllc",
      lane: "enterprise_services",
      publicSlug: "strategy-session-60",
      title: "Strategy Session · 60 Minutes",
      summary: "Full decision session for roadmap shaping, offer architecture, conversion design, or operational correction.",
      displayedPrice: "$350",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Best for teams that want a concrete next-state architecture and execution path.",
      ctaLabel: "Book Strategy Session",
      badges: ["Decision Session"],
    },
    {
      brand: "jaypventuresllc",
      lane: "enterprise_services",
      publicSlug: "systems-deep-dive-90",
      title: "Systems Deep Dive · 90 Minutes",
      summary: "High-resolution session for diagnosing workflows, routing, data gaps, automation risk, and platform friction.",
      displayedPrice: "$500",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use when the business already has complexity, fragmentation, or measurable drag.",
      ctaLabel: "Book Deep Dive",
      badges: ["Audit Lens"],
    },
    {
      brand: "jaypventuresllc",
      lane: "enterprise_services",
      publicSlug: "business-growth-sprint",
      title: "Business Growth Sprint",
      summary: "A focused enterprise sprint that restructures the revenue and operating system around a specific growth constraint.",
      displayedPrice: "$5,000",
      ctaType: "application",
      ctaDestination: enterpriseApplication,
      qualificationRule: "Application-led for teams with active traction and a clear growth bottleneck.",
      ctaLabel: "Apply for Sprint",
      badges: ["High-Touch", "Application"],
    },
    {
      brand: "jaypventuresllc",
      lane: "enterprise_services",
      publicSlug: "done-for-you-systems-build",
      title: "Done-For-You Systems Build",
      summary: "Full-stack architecture and implementation for businesses that need the operating system designed and shipped with rigor.",
      displayedPrice: "$15,000+",
      ctaType: "application",
      ctaDestination: enterpriseApplication,
      qualificationRule: "Reserved for qualified build engagements with clear commercial scope.",
      ctaLabel: "Request Build Scope",
      badges: ["Flagship Offer", "Application"],
    },
  ];
}

export function getCreatorOffers(env: Env): Offer[] {
  return [
    {
      brand: "jaypventures",
      lane: "creator_services",
      publicSlug: "fit-call-15",
      title: "jaypventures creator Fit Call · 15 Minutes",
      summary: "A quick clarity call for creators, operators, and collaborators entering the ecosystem.",
      displayedPrice: "Free",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Start here if you want the right creator lane before buying anything deeper.",
      ctaLabel: "Book Creator Fit Call",
      badges: ["Entry Point"],
    },
    {
      brand: "jaypventures",
      lane: "creator_services",
      publicSlug: "strategy-session-30",
      title: "Strategy Session · 30 Minutes",
      summary: "Offer architecture, content planning, and audience-to-revenue conversion guidance.",
      displayedPrice: "$125",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Best for creators and personal brands ready to organize monetization around a real strategy.",
      ctaLabel: "Book Strategy Session",
      badges: ["Creator Strategy"],
    },
    {
      brand: "jaypventures",
      lane: "creator_services",
      publicSlug: "monetization-session-60",
      title: "Monetization Session · 60 Minutes",
      summary: "A working session focused on paid offers, memberships, CTA design, and retention loops.",
      displayedPrice: "$250",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use when you already have audience attention and need stronger revenue structure.",
      ctaLabel: "Book Monetization Session",
      badges: ["Revenue Focus"],
    },
    {
      brand: "jaypventures",
      lane: "creator_services",
      publicSlug: "creator-build-sprint",
      title: "Creator Build Sprint",
      summary: "Build the creator-facing funnel, membership logic, and offer stack around a sharper commercial identity.",
      displayedPrice: "$1,250",
      ctaType: "application",
      ctaDestination: creatorApplication,
      qualificationRule: "Application-led for creators who want a direct system build, not just advice.",
      ctaLabel: "Apply for Creator Sprint",
      badges: ["Build Offer", "Application"],
    },
    {
      brand: "jaypventures",
      lane: "creator_services",
      publicSlug: "monthly-creator-operations",
      title: "Monthly Creator Operations",
      summary: "Ongoing support for content rhythm, creator offers, and ecosystem momentum across the month.",
      displayedPrice: "$300/mo",
      ctaType: "application",
      ctaDestination: creatorApplication,
      qualificationRule: "Application-led for creators who want recurring operating support.",
      ctaLabel: "Apply for Monthly Support",
      badges: ["Recurring"],
    },
  ];
}

export function getMusicOffers(env: Env): Offer[] {
  return [
    {
      brand: "jaypventures_music",
      lane: "music",
      publicSlug: "fit-call-15",
      title: "JayPVentures Music Fit Call · 15 Minutes",
      summary: "Quick alignment call for artists, collaborators, and music-adjacent partnerships.",
      displayedPrice: "Free",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use for first-pass creative and collaboration fit.",
      ctaLabel: "Book Music Fit Call",
    },
    {
      brand: "jaypventures_music",
      lane: "music",
      publicSlug: "production-strategy-30",
      title: "Production Strategy · 30 Minutes",
      summary: "Planning session for music output, release sequencing, and creator-to-music brand alignment.",
      displayedPrice: "$125",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Best for artists who need strategic clarity before execution.",
      ctaLabel: "Book Production Strategy",
    },
    {
      brand: "jaypventures_music",
      lane: "music",
      publicSlug: "creative-systems-session-60",
      title: "Creative Systems Session · 60 Minutes",
      summary: "Structure the creative workflow, release cadence, and ecosystem fit around the artist identity.",
      displayedPrice: "$250",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use when music output needs stronger systems and continuity.",
      ctaLabel: "Book Creative Systems Session",
    },
    {
      brand: "jaypventures_music",
      lane: "music",
      publicSlug: "collaboration-session-60",
      title: "Collaboration Session · 60 Minutes",
      summary: "Working session for aligned collaborative opportunities, release positioning, and cross-brand programming.",
      displayedPrice: "$175",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use for active collaboration planning with clear intent.",
      ctaLabel: "Book Collaboration Session",
    },
    {
      brand: "jaypventures_music",
      lane: "music",
      publicSlug: "project-build-sprint",
      title: "Project Build Sprint",
      summary: "A focused sprint to package a music-driven release or creator-music campaign into a working commercial system.",
      displayedPrice: "$1,500",
      ctaType: "application",
      ctaDestination: musicApplication,
      qualificationRule: "Application-led for artists or teams ready to build a full launch structure.",
      ctaLabel: "Apply for Music Sprint",
    },
    {
      brand: "jaypventures_music",
      lane: "music",
      publicSlug: "monthly-creative-direction",
      title: "Monthly Creative Direction",
      summary: "Recurring support for releases, partnerships, content rhythm, and creator-music alignment.",
      displayedPrice: "$300/mo",
      ctaType: "application",
      ctaDestination: musicApplication,
      qualificationRule: "Application-led for recurring strategic support.",
      ctaLabel: "Apply for Monthly Direction",
    },
  ];
}

export function getTravelOffers(env: Env): Offer[] {
  return [
    {
      brand: "jaypventures_travel",
      lane: "travel",
      publicSlug: "trip-inquiry-15",
      title: "JayPVentures Travel Trip Inquiry · 15 Minutes",
      summary: "Intro call for custom travel ideas, small-group planning, or travel-aligned collaboration.",
      displayedPrice: "Free",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Start here for fit and route clarity.",
      ctaLabel: "Book Travel Inquiry",
    },
    {
      brand: "jaypventures_travel",
      lane: "travel",
      publicSlug: "travel-planning-session-30",
      title: "Travel Planning Session · 30 Minutes",
      summary: "One-on-one planning support for itinerary shaping, trip structure, and experience design.",
      displayedPrice: "$150",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Best for custom travel plans with defined intent.",
      ctaLabel: "Book Travel Planning",
    },
    {
      brand: "jaypventures_travel",
      lane: "travel",
      publicSlug: "group-strategy-session-60",
      title: "Group Strategy Session · 60 Minutes",
      summary: "Plan a group travel experience with better structure, logistics, and aligned expectations.",
      displayedPrice: "$300",
      ctaType: "booking",
      ctaDestination: env.MICROSOFT_BOOKINGS_URL,
      qualificationRule: "Use when coordination complexity starts to matter.",
      ctaLabel: "Book Group Strategy Session",
    },
    {
      brand: "jaypventures_travel",
      lane: "travel",
      publicSlug: "custom-itinerary-build",
      title: "Custom Itinerary Build",
      summary: "A fully shaped travel plan designed around cadence, constraints, and experience quality.",
      displayedPrice: "$500",
      ctaType: "application",
      ctaDestination: travelApplication,
      qualificationRule: "Application-led for fully custom work with layered logistics.",
      ctaLabel: "Request Itinerary Build",
    },
    {
      brand: "jaypventures_travel",
      lane: "travel",
      publicSlug: "group-trip-operations-management",
      title: "Group Trip Operations Management",
      summary: "High-touch planning and coordination for more complex group or multi-phase travel execution.",
      displayedPrice: "$2,500",
      ctaType: "application",
      ctaDestination: travelApplication,
      qualificationRule: "Application-led for larger or operationally intensive travel projects.",
      ctaLabel: "Apply for Travel Ops",
    },
  ];
}

export function getMembershipTiers(): MembershipTier[] {
  return [
    {
      slug: "core",
      title: "All Ventures Access · Core",
      price: "$39/mo",
      audience: "Audience members and early supporters who want recurring access to the ecosystem.",
      summary: "Entry tier for recurring access, curated updates, and the first layer of venture benefits.",
      includes: [
        "Recurring ecosystem updates",
        "Early access to drops and shifts",
        "Priority invitations to selected public experiences",
      ],
      checkoutKey: "core",
    },
    {
      slug: "plus",
      title: "All Ventures Access · Plus",
      price: "$79/mo",
      audience: "Members who want deeper access, stronger proximity, and more structured participation.",
      summary: "Expands the access layer with richer member benefits and more active ecosystem connection.",
      includes: [
        "Everything in Core",
        "Expanded venture updates and member-first drops",
        "Higher-priority access to select creator and ecosystem opportunities",
      ],
      checkoutKey: "plus",
    },
    {
      slug: "inner-circle",
      title: "All Ventures Access · Inner Circle",
      price: "$199/mo",
      audience: "High-trust members who want the premium layer of access, transparency, and gated surfaces.",
      summary: "The highest membership tier, designed around premium visibility into the ecosystem and gated command-center style access.",
      includes: [
        "Everything in Plus",
        "Inner Circle Transparency Portal access",
        "Creator Command Center access where eligible",
        "Premium routing and ecosystem priority",
      ],
      checkoutKey: "innerCircle",
    },
  ];
}

export function getMembershipCheckoutLinks(env: Env): Record<MembershipTier["checkoutKey"], string> {
  return {
    core: env.STRIPE_ALL_VENTURES_CORE_URL,
    plus: env.STRIPE_ALL_VENTURES_PLUS_URL,
    innerCircle: env.STRIPE_ALL_VENTURES_INNER_CIRCLE_URL,
  };
}

export function getAllOffers(env: Env): Offer[] {
  return [
    ...getEnterpriseOffers(env),
    ...getCreatorOffers(env),
    ...getMusicOffers(env),
    ...getTravelOffers(env),
  ];
}
