export interface Env {
    JPV_INTERNAL_TEST_TOKEN?: string;
  ENVIRONMENT: "local" | "dev" | "prod";

  INTAKE_HMAC_SECRET: string;
  INTAKE_HMAC_SECRET_SECRET_NAME?: string;

  SHAREPOINT_SITE_ID?: string;
  SHAREPOINT_LIST_ID?: string;
  SHAREPOINT_MEMBERS_LIST_ID?: string;
  SHAREPOINT_ACCESS_TOKEN?: string;
  SHAREPOINT_ACCESS_TOKEN_SECRET_NAME?: string;

  STRIPE_SECRET_KEY?: string;
  STRIPE_SECRET_KEY_SECRET_NAME?: string;
  STRIPE_WEBHOOK_SECRET?: string;

  MEMBERSTACK_WEBHOOK_SECRET?: string;
  MEMBERSTACK_JWT_PUBLIC_KEY?: string;
  MEMBERSTACK_JWT_PUBLIC_KEY_SECRET_NAME?: string;

  EMAIL_API_KEY?: string;

  DATALAKE_ENDPOINT?: string;
  DATALAKE_TOKEN?: string;
  DATALAKE_TOKEN_SECRET_NAME?: string;

  IDEMPOTENCY_KV?: KVNamespace;
  METRICS_KV?: KVNamespace;
  CREATOR_DATA_KV?: KVNamespace;
  INNER_CIRCLE_MEMBER_KV?: KVNamespace;
  ADMIN_UPLOAD_TOKEN?: string;
  WORKER_EVENTS_QUEUE?: Queue<unknown>;

  DISCORD_BOT_TOKEN?: string;
  DISCORD_GUILD_ID?: string;
  DISCORD_COMMUNITY_ROLE_ID?: string;
  DISCORD_VIP_ROLE_ID?: string;
  DISCORD_INNER_CIRCLE_ROLE_ID?: string;

  AZURE_KEY_VAULT_URL?: string;
  AZURE_TENANT_ID?: string;
  AZURE_CLIENT_ID?: string;
  AZURE_CLIENT_SECRET?: string;
  APPINSIGHTS_CONNECTION_STRING?: string;
  AZURE_ARCHIVE_ENDPOINT?: string;
  AZURE_ARCHIVE_TOKEN?: string;
  AZURE_ARCHIVE_TOKEN_SECRET_NAME?: string;
}

